language: go
go:
  - 1.13.x

before_install:
  - sudo apt-get update
  - docker-compose --version
  - pip install docker-compose --upgrade
  - docker-compose --version
install:
  - docker-compose up -d --build
  - docker-compose ps
script:
  - bash ./.travis/linters.sh
  - go test -v ./...
  - bash ./.travis/check-service-status.sh

notifications:
  email: false

after_success:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker-compose images

env:
  global:
    - GO111MODULE=on
  matrix:
    - DOCKER_CONTENT_TRUST=1

services:
  - docker

branches:
  only:
    - master
