language: go
go:
  - 1.13.x

before_install:
  - sudo apt-get update
  - docker-compose --version
  - pip install --user docker-compose --upgrade
  - docker-compose --version
install:
  - docker-compose up -d --build
  - docker-compose ps
before_script:
  - bash chmod +x ./.travis/linters.sh
  - bash chmod +x ./.travis/check-service-status.sh
script:
  - bash ./.travis/linters.sh
  - go test -v ./...
  - bash ./.travis/check-service-status.sh

notifications:
  email: false
  slack:
    rooms:
      - optimum-team:GycletOWK4Kt95GktwYwfUMp#build

after_success:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker-compose images

env:
  global:
    - GO111MODULE=on
  matrix:
    - DOCKER_CONTENT_TRUST=1

services:
  - docker

branches:
  only:
    - master
